/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Contador01;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      int pirueta = 1;
      while (pirueta<12) {
              pirueta++;
              if (pirueta==5 || pirueta == 8) {
                 continue;
              }
              if (pirueta == 10) {
                  break;
              }
          System.out.println("Piruetaaa"+ pirueta);
      
      } 
    }
}
